### ISSUE TITLE
[Web][Jobseeker] Not asking to select resume while applying for job

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#147]
1. Login as Jobseeker
2. Click on title of internally posted job (not imported job)
3. Click on [Apply Job]
4. Confirm job application popup displayed

Actual result:
There is no option to select resume. Only "Resume Title" and "Cover letter" is displayed.

Expected result:
Show all resumes available along with "Resume Title" and "Cover letter"

![image](https://user-images.githubusercontent.com/101229315/212792244-e0a5c2fe-ded5-478b-aa6b-03aa35b76a96.png)

**Comment by eraytech** [comment]
Issue is still repeating

**Comment by Abhinavgunda25** [comment]
Issue is resolved., Please check

**Comment by Abhinavgunda25** [comment]
1. User select resume before submitting
![t-147](https://user-images.githubusercontent.com/49630766/236387067-2f9aa05c-b10a-4bf1-bb98-653761823a2a.PNG)

**Comment by eraytech** [comment]
Issue still repeating

![image](https://user-images.githubusercontent.com/101229315/236637160-02ecf1eb-6c65-4c51-a9ff-218c06e2a07f.png)

**Comment by eraytech** [comment]
UI displaying to 'Add Resume', but unable to add resume because of non-functioning of 'submit' button after uploading resume

**Comment by Abhinavgunda25** [comment]
With a same id only i have added resumes. Please check video
[screen-capture.webm](https://github.com/gak112/DearJobTesting/assets/49630766/eb2384b2-d622-4d37-ba8b-1d123c28d0cb)

**Comment by eraytech** [comment]
verified and working
