### ISSUE TITLE
[Web/Mobile] Number formatting needs change through out website

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#169]
Observe $ amount any where in website. Number format is needs to be changed.

Ex: 
1)  $ 62556.0 - 80721.0 Per Year --> **$ 62,556 - 80,721 Per Year** (decimals can be removed and comma separated at thousands)
![image](https://user-images.githubusercontent.com/101229315/213259554-751addee-df68-4782-95b1-1bc5b7250ec5.png)

2)  $ 35.3800010681152 - 52.7799987792969 hourly ---> Change to: **$ 35 - 53 hourly** (change to nearest integer)

![image](https://user-images.githubusercontent.com/101229315/213260341-86d88b7f-4182-42e4-9c47-cb98abc049e6.png)

3) If Salary is not available, display "**Salary not mentioned**"

**Comment by Abhinavgunda25** [comment]
issue is resolved

**Comment by eraytech** [comment]
Issue still exists. 
Ex:
$ 62556.0 - 80721.0 Per Year --> $ 62,556 - 80,721 Per Year (decimals can be removed and comma separated at thousands)

![image](https://user-images.githubusercontent.com/101229315/213779522-f1aed2a3-bdad-4cb1-9d87-c149264194a4.png)

**Comment by Abhinavgunda25** [comment]
Issue is resolved., Please check

**Comment by Abhinavgunda25** [comment]
Issue is resolved., Please check

**Comment by eraytech** [comment]
Verified and closed
